// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  a1niveauSidebar: [{ type: 'category', label: 'A1 Niveau', items: [
    { type: 'autogenerated', dirName: 'a1niveau' }
  ] }],
  
  a2niveauSidebar: [{ type: 'category', label: 'A2 Niveau', items: [
    { type: 'autogenerated', dirName: 'a2niveau' }
  ] }],
  
  b1niveauSidebar: [{ type: 'category', label: 'B1 Niveau', items: [
    { type: 'autogenerated', dirName: 'b1niveau' }
  ] }],
  
  b2niveauSidebar: [{ type: 'category', label: 'B2 Niveau', items: [
    { type: 'autogenerated', dirName: 'b2niveau' }
  ] }],
};

export default sidebars;